site_name: ChileSec
site_description: >-
  Uniting New Mexico's Cybersecurity Community.

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - no-zoom
      auto_caption: true
      caption_position: bottom
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  # custom_dir: overrides
  # icon:
    # repo: fontawesome/brands/github
  # logo: assets/rba_logo_small.png
  # favicon: assets/favicon-32x32.png
  features:
    - announce.dismiss
    - content.code.copy
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.follow
    - navigation.tracking
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: custom
      # accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# extra_css:
  # - stylesheets/extra.css

# extra:
#   consent:
#     title: Cookie consent
#     actions:
#       - accept
#       - reject
#       - manage
#     description: >-
#       We use cookies to recognize your repeated visits and preferences, as well
#       as to measure the effectiveness of our documentation and whether users
#       find what they're searching for. With your consent, you're helping us to
#       make our documentation better.
#   analytics:
#     provider: google
#     property: G-NE2FQCZZ3E
#     feedback:
#       title: Was this page helpful?
#       ratings:
#         - icon: material/emoticon-happy-outline
#           name: This page was helpful
#           data: 1
#           note: >-
#             Thanks for your feedback!
#         - icon: material/emoticon-sad-outline
#           name: This page could be improved
#           data: 0
#           note: >-
#             Thanks for your feedback!
#  social:
#    - icon: material/google-drive
#      link: https://drive.google.com/drive/folders/1t514OI5obxInEmM8PzQZz-JIgcL2LE9G
#      name: The RBA Community Google Drive
#    - icon: fontawesome/brands/linkedin
#      link: https://www.linkedin.com/groups/12702283/
#      name: The RBA Community LinkedIn Group
#    - icon: fontawesome/brands/github
#      link: https://splunk.github.io/rba/
#      name: The RBA Community GitHub
#    - icon: fontawesome/brands/slack
#      link: https://outpost-security.com/slack/
#      name: The RBA Community Slack

copyright: >
  Copyright &copy; 2023 ChileSec –
#  <a href="#__consent">Change cookie settings</a>

nav:
  - Home: index.md
#  - The Risky Times: risky-times/index.md
#  - Video Library: library/index.md
#  - Community Involvment: 
#      - Contributing: community/contribute.md
#      - RBA Champions: community/rba-champions.md
#  - Partner Support:
#      - partners/index.md
#      - Outpost Security: partners/outpost.md
#      - SP6: partners/sp6.md
#      - Support The RBA Community: partners/support.md